### ISSUE TITLE
ByteVector should be Long indexed to allow working with vectors over 2g

### ISSUE THREAD

**Issue by mpilquist** [scodec/scodec-bits#17]
Currently, BitVector is Long indexed whereas ByteVector is Int indexed. We should consider making ByteVector Long indexed to remove the 2g limitation.

This came up in https://github.com/scodec/scodec/issues/9.

If I recall correctly, we left ByteVector Int indexed because all of the source data structures are Int indexed (e.g., Array, ByteBuffer, GenTraversableOnce). However, I'd like to support getting a ByteVector for a memory mapped file that's over 2g -- using a ByteVector that's backed by a chunk list where each chunk is a memory mapped offset.

Alternatively, if we decide to leave ByteVector as Int indexed, I'd like to capture the rationale here.

**Comment by djspiewak** [comment]
@mpilquist Is this blocked on scalaz-stream?  I don't particularly need `Long` indexing for `ByteVector`, I just want to make sure you're not blocked on us.

**Comment by mpilquist** [comment]
@djspiewak Not particularly, though I did recently discuss this with @pchiusano. To minimize disruption, I'm planning on releasing this such that it can be included as part of the scalaz-stream release post new algebra and project rename, etc.

**Comment by djspiewak** [comment]
@mpilquist Alrighty! Just wanted to make sure you weren't waiting on us or anything I could take care of.

**Comment by mpilquist** [comment]
Fixed in 1.1.0, which was released today! Sorry this took 18 months to get released.
