### ISSUE TITLE
CI fails because of missing GPG keys

### ISSUE THREAD

**Issue by sideeffffect** [scodec/scodec-bits#213]
The CI build https://github.com/scodec/scodec-bits/runs/998085335?check_suite_focus=true#step:27:312 fails with
```
[error] (coreJVM / publish / packagedArtifacts) GPG reported an error. Artifacts won't be signed.
```
This seems to be just like an oversight, could you @mpilquist add those keys?

For the publis to work, there should be env variables `PGP_PASSPHRASE`, `PGP_SECRET`, `SONATYPE_PASSWORD` and `SONATYPE_USERNAME`

**Comment by mpilquist** [comment]
Yeah, looks like I never finished setting up the secrets. I'll fix soon, thanks!

**Comment by mpilquist** [comment]
Fixed now
