### ISSUE TITLE
Increase Scala.js support to include crypto methods

### ISSUE THREAD

**Issue by armanbilge** [scodec/scodec-bits#300]
Currently crypto-related methods fail at Scala.js link time due to their use of unsupported Java classes. This came up in https://github.com/tpolecat/skunk/pull/515.

I'd like to add support for these, but there are a couple things to consider.

1. Should we support both Node.js and browser environments? The easiest way to do so would be to use the [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) available in browsers and [experimentally available](https://nodejs.org/api/webcrypto.html#webcrypto_web_crypto_api) in Node.js 15+.
2. The Web Crypto API is completely asynchronous (i.e. returns Javascript Promises). I think the way to handle this is to introduce new methods that return `Future` and implement them appropriately on each platform.
3. Alternatively, support only Node.js which has synchronous implementations available for at least some of these methods.

Thanks in advance for your thoughts.

**Comment by mpilquist** [comment]
:+1: to Web Crypto

We could keep synchronous methods as JVM only and make the async ones cross platform, though not entirely sure how we'd implement JVM versions -- I guess we'd need an implicit `ExecutionContext`.

**Comment by armanbilge** [comment]
Thanks for 👍 I did have some more time to think about this, you are okay with introducing impure `Future` methods to scodec? I'm not too crazy about it.

> though not entirely sure how we'd implement JVM versions

I'm pretty sure you can construct a successful (pure) `Future` without an EC, could be wrong though. Ironically, I think it's the JS methods that will need an execution context, to convert the Promise to a Future.

Just to throw out one more idea: http4s, Skunk, and scodec all need crypto on JS. What if we made a new cross-platform library defining a `Crypto[F]` type class in its zero-dependency kernel and implementations in another module? Then `scodec` can provide a pure API for its crypto methods with only a dependency on `Crypto[F]` and furthermore we can share all this code between the three libs and reduce the need for "platforming".

**Comment by armanbilge** [comment]
> zero-dependency kernel

Hmm, this seems dumb 😆 the dependency it would need is probably `scodec-bits`. Which means, `scodec-bits` would probably be the only possible home for a `Crypto[F]`?

**Comment by armanbilge** [comment]
Closing; this problem is being addressed in https://github.com/typelevel/bobcats.
