### ISSUE TITLE
Release for Scala 2.12.0-M3?

### ISSUE THREAD

**Issue by SethTisue** [scodec/scodec-bits#43]
The Scala team would be interested in hearing if you encounter any trouble.

**Comment by mpilquist** [comment]
Thanks for the reminder. Published to Sonatype just now:

    "org.scodec" %% "scodec-bits" % "1.0.10"

**Comment by SethTisue** [comment]
awesome, thanks! https://github.com/scala/make-release-notes/commit/4eac558dcf8f22eb065f267ba310b328cfca36b3
