### ISSUE TITLE
Add filter to ByteVector

### ISSUE THREAD

**Issue by searler** [scodec/scodec-bits#48]
I have a need to remove escape characters from a ByteVector. This is easy enough to implement, but has  poor performance. 

My use case is a custom "wireshark" that uses the pcap functionality to capture and display the operation of a networked API. The de-escape code is ~75% of the total runtime!

My first attempt was modeled on the algorithms seen within the scodec codebase.

```
private val escape = hex"10"

private def unescaped(bytes: ByteVector): ByteVector = unescaped(bytes,ByteVector.empty)

  @tailrec private def unescaped(bytes: ByteVector, accum:ByteVector): ByteVector = {
    bytes indexOfSlice (escape) match {
      case -1 => accum ++ bytes
      case idx =>
           unescaped(bytes.drop(idx + 2), accum ++ bytes.take(idx) ++ bytes.slice(idx + 1, idx + 2))
    }
  }
```

The following is much simpler and about 25% faster (although less general)

```
ByteVector(bytes.toSeq.filterNot { _ == 0x10 })
```

The next step would be to build a set of micro-benchmarks and test a variety of algorithms.

Presumably a variant of the map() code is needed to efficiently implement filter

**Comment by mpilquist** [comment]
@searler Are you still in need of an efficient `filter`?

**Comment by searler** [comment]
I ended up using a mutable java.nio.ByteBuffer.

So I do not "need" an efficient filter but would like to learn how to express an efficient filter using the scodec idioms. I would happy to attempt an implementation but need some pointers as to how to approach the task.

Thanks

**Comment by mpilquist** [comment]
Take a look at `foreachV` -- I'd start by using that basic recursive structure, changing it so a filtered vector is returned and the `Chunk(bs)` handler does filtering. To do the latter, add a `filter` method to the `View` class with a definitely implementation that's defined in terms of `apply`. Then override that definition in the `AtArray` and `AtByteBuffer` subtypes. That should end up fast. :)

**Comment by searler** [comment]
I found all the relevant code, thank you.
However, the implementation would require a lot of changes.
That seems inappropriate, given the limited use case for this functionality.

Even my project would not use it since I moved the relevant filter logic into the framing code that is implemented using akka streams.
