### ISSUE TITLE
scodec.bits.ByteVector does not have an .unapply method

### ISSUE THREAD

**Issue by lihaoyi** [scodec/scodec-bits#52]
Ironically, while `Array` has a borked `==` and working `unapply`, `ByteVector` has a working `==` and non-working `unapply`. Bumped into this when trying to convert my `fastparse.byte` test suite from `Array[Byte]` to `ByteVector`, which necessitated a lot of changes like:

```scala
-        val capture1(Array(1, 1, 1)) = hexBytes("01 01 01 02")
+        val capture1(res1) = hexBytes("01 01 01 02")
+        assert(res1 == ByteVector(1, 1, 1))
```

Even though it's probably not useful in the general case for production code, it would still be nice to have an `unapply` I can use for easy unit testing and doc-demos

**Comment by mpilquist** [comment]
Thanks. I'm on board with adding `unapplySeq` to `ByteVector`. I can probably do this tomorrow.
