### ISSUE TITLE
Convert .grouped to return an Iterator instead of a Stream?

### ISSUE THREAD

**Issue by lihaoyi** [scodec/scodec-bits#55]
That would better match up with the collections in the standard library, which all return Iterator. Current inefficient workaround is `.toArray.grouped.map(ByteVector.view)`, though with a bit more boilerplate less wasteful version could be written

**Comment by mpilquist** [comment]
👍 for either 1.2 or 2.0 -- whatever comes next. Let's keep this issue open until we decide breaking binary compatibility makes sense.
