### ISSUE TITLE
Add UUID to/from ByteVector transformation?

### ISSUE THREAD

**Issue by BardurArantsson** [scodec/scodec-bits#56]
Given that UUID is already part of the JDK platform, I'd like to add a UUID<->ByteVector conversion functions. I'd be happy to provide an implementation, though it's almost trivial.

EDIT: Rationale: AFAICT it's more efficient to do so directly in the ByteVector (with access to internals), and since the relevant bits of UUID are also part of scala.js I don't really see any issues with doing it.

**Comment by mpilquist** [comment]
:+1:

We could lift the implementation from https://github.com/scodec/scodec/blob/30fabb2dfd61e709b931490d10eeae987219764a/shared/src/main/scala/scodec/codecs/UuidCodec.scala

**Comment by BardurArantsson** [comment]
Ah, right, though I'd probably do it by using the ByteVector internal methods (see my edit).

**Comment by BardurArantsson** [comment]
... but I'd definitely want to change scodec to use the new implementation.

**Comment by mpilquist** [comment]
Yep sounds good. PR would be great if you have time.

**Comment by BardurArantsson** [comment]
Will do a PR shortly -- right in the middle of something which I don't want to context-switch away from ATM. :)
