### ISSUE TITLE
Release 1.1.2?

### ISSUE THREAD

**Issue by BardurArantsson** [scodec/scodec-bits#62]
It seems 2.12.0-RC2 was a bit further off than (I) expected.

Any chance you could do a 1.1.2 release?

**Comment by mpilquist** [comment]
Yep, will release tonight. RC2 took longer than I expected too.

**Comment by mpilquist** [comment]
On Sonatype and should be on Central soon

**Comment by BardurArantsson** [comment]
Thanks!
