### ISSUE TITLE
Release for Scala 2.12.0

### ISSUE THREAD

**Issue by larsrh** [scodec/scodec-bits#65]
Required for a 2.12 build of fastparse (lihaoyi/fastparse#133). Would be great if you could release a 2.12 build of the existing version `1.1.2`.

**Comment by mpilquist** [comment]
Yep will do, just waiting on ScalaCheck and ScalaTest

**Comment by larsrh** [comment]
Those are released now.

**Comment by mpilquist** [comment]
scodec-bits 1.1.2 has been published for Scala 2.12.0
