### ISSUE TITLE
dependency on scodec-build SNAPSHOT

### ISSUE THREAD

**Issue by SethTisue** [scodec/scodec-bits#82]
cb756ae4f7a7dfa1ce61dc5024719007a930a6c2 has:

```diff
-addSbtPlugin("org.scodec" % "scodec-build" % "1.8.0")
+addSbtPlugin("org.scodec" % "scodec-build" % "1.9.0-SNAPSHOT")
```

this is problematic for the Scala community build:

```
[scodec-bits] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[scodec-bits] [warn] 	::          UNRESOLVED DEPENDENCIES         ::
[scodec-bits] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[scodec-bits] [warn] 	:: org.scodec#scodec-build;1.9.0-SNAPSHOT: not found
[scodec-bits] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

it might be addressable at our end by adding a resolver where this snapshot can be found, but adding resolvers is a bit cumbersome and could slow down the build overall. is it necessary at your end to have the -SNAPSHOT dependency at all?

**Comment by mpilquist** [comment]
Ouch, that's something I didn't expect. I was going to get scodec-core working with the new scodec-build and then release 1.9. I'm most of the way through that so it will be another couple of hours most likely.

**Comment by SethTisue** [comment]
ok, no rush. I froze it for now: scala/community-builds@66ca54cce39a6c114f2648023ffbe3fed69dabbe

**Comment by mpilquist** [comment]
Thanks, this should be fixed now.
