### ISSUE TITLE
base58 support

### ISSUE THREAD

**Issue by alari** [scodec/scodec-bits#83]
Base58 looks like a subset of Base64 alphabet. It's very useful for both URLs and user-facing addresses, like in crypto world.

https://en.wikipedia.org/wiki/Base58

**Comment by Christewart** [comment]
Implementation in bitcoin-s 

https://github.com/bitcoin-s/bitcoin-s-core/blob/2b087a131b676439a177a29f4dcb92b5f5909745/core/src/main/scala/org/bitcoins/core/util/Base58.scala

**Comment by mpilquist** [comment]
Fixed by #95. Feel free to open a PR with improvements from other implementations.
